# Generated by Django 5.0.4 on 2024-04-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='last_login_timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
