# Generated by Django 5.0.4 on 2024-04-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_bot_app', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='successors',
            field=models.ManyToManyField(blank=True, related_name='predecessors', to='instagram_bot_app.menu'),
        ),
    ]
