# Generated by Django 5.0.4 on 2024-04-28 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_bot_app', '0004_menu_successors'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('payload', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('URL', 'URL'), ('BUTTON', 'Button')], max_length=6)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram_bot_app.menu')),
            ],
        ),
    ]
