# Generated by Django 5.0.4 on 2024-04-28 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_bot_app', '0005_optionsmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='successors',
        ),
        migrations.AddField(
            model_name='menu',
            name='successor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='instagram_bot_app.menu'),
        ),
    ]
