# Generated by Django 5.0.4 on 2024-04-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_bot_app', '0007_rename_successor_menu_preceder_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='preceder_of',
            new_name='successor_of',
        ),
    ]
