# Generated by Django 5.0.4 on 2024-04-28 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_bot_app', '0009_alter_menu_successor_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='successor_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successor_of', to='instagram_bot_app.optionsmenu', unique=True),
        ),
    ]
