# Generated by Django 5.0.4 on 2024-04-28 07:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_bot_app', '0010_alter_menu_successor_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionsmenu',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optionsmenu',
            name='payload',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
