# Generated by Django 5.0.4 on 2024-04-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_bot_app', '0011_optionsmenu_url_alter_optionsmenu_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionsmenu',
            name='url',
        ),
    ]
